### ISSUE TITLE
Feature: Option to display only icons

### ISSUE THREAD

**Issue by kashban** [piruin/quickaction#10]
The old version of QuickAction3D adjusted the height if no action item texts were provided. This version leaves an empty space below the icons instead, which is a bit unfortunate. 
![quickaction3dwithouttext](https://user-images.githubusercontent.com/6595407/27374978-082aabe2-566e-11e7-8b68-ec240331dd40.png)

**Comment by piruin** [comment]
@kashban Sorry for reply late,

Try it on version `2.3 ` . Thank for good feature.

**Comment by kashban** [comment]
@piruin Will do, thanks!
