### ISSUE TITLE
Why  API level 19 is minimum ?

### ISSUE THREAD

**Issue by milaptank** [piruin/quickaction#13]
Hello Why API level 19 as minimum API ?
you can run this lib as API 16 as minimum actually I have used this in API 16 and working fine

**Comment by piruin** [comment]
@milaptank I don't even remember why. If not found any issue I will change minimum API to 16 on next release. Thank for suggestion

**Comment by milaptank** [comment]
there is only one need for API 19 is
In ActionItem.java
```java 
   @RequiresApi(api = Build.VERSION_CODES.KITKAT)
   @Override public int hashCode() {
     return Objects.hash(actionId);
    }


Which is mostly negligible

**Comment by piruin** [comment]
I tried to change `minSdkVersion` to 16 and then remember that I don't wanna go back to Java6. Because **java6** may cause to much effort to maintain this project in future
  
Sorry for not support your request

**Comment by milaptank** [comment]
Hey one more help from you 
can you create **hacktoberfest** label and assing to all issue 
See
https://hacktoberfest.digitalocean.com/ you will get Tee

**Comment by mustafaozhan** [comment]
@milaptank  Just for your information guys forked and created with a version for min `sdk-version 16` [here](https://github.com/mustafaozhan/quickaction/blob/master/README.md)
