### ISSUE TITLE
Error with library version 2.1

### ISSUE THREAD

**Issue by joshvarun** [piruin/quickaction#16]
![crop](https://user-images.githubusercontent.com/15075336/33769297-9d9b728a-dc4f-11e7-890a-945d07a55dc2.png)
Hi, I've added this dependency in my gradle file compile 'com.github.piruin:quickaction:2.1'

But I'm getting errors as seen in image.

Please help!

**Comment by piruin** [comment]
@joshvarun can u try version `2.4.1`
