### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by adelemam** [piruin/quickaction#18]
We have issue adding your awesome control with a recycler view , it working great in english but when converting to Arabic , it doesn't show properly  as arrow doesn't point to the selected pager item.

If you are busy you can even give us a clue how to solve it. thanks

**Comment by piruin** [comment]
QuickAction's arrow try point at center of anchor view. With Non-English text, `TextView`'s width usually longer than we expected. that may cause of this issue.
