### ISSUE TITLE
:minSdkVersion 16 cannot be smaller than version 19

### ISSUE THREAD

**Issue by mike-maina** [piruin/quickaction#19]
Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [com.github.piruin:quickaction:2.4.2] C:\Users\user\.gradle\caches\transforms-1\files-1.1\quickaction-2.4.2.aar\4b3492bf2864c3cd45fd1a91891e7382\AndroidManifest.xml as the library might be using APIs not available in 16
	Suggestion: use a compatible library with a minSdk of at most 16,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="me.piruin.quickaction" to force usage (may lead to runtime failures)

**Comment by piruin** [comment]
QuickAction is support minSdk = 19, Sorry for your inconvenience. See #13

**Comment by mike-maina** [comment]
@RequiresApi(api = Build.VERSION_CODES.KITKAT)
   @Override public int hashCode() {
     return Objects.hash(actionId);
    }

I removed  this line and its working fine

**Comment by piruin** [comment]
@mike-maina, 
you may folk and publish `sdk-version 16` version if you like, *JitPack* is easily to. 🤝

**Comment by mustafaozhan** [comment]
@piruin isn't `support minsdk 16 with java 8 #13 #19` included in 
`implementation 'me.piruin:quickaction:2.4.2'`

**Comment by mustafaozhan** [comment]
@mike-maina Just for your information guys forked and created with a version for min `sdk-version 16` [here](https://github.com/mustafaozhan/quickaction/blob/master/README.md)
