### ISSUE TITLE
Item Widths 

### ISSUE THREAD

**Issue by mustafaozhan** [piruin/quickaction#22]
Hello,

First of all thank you for the nice library. I use it in my project  with `VERTICAL` mode and I have experienced that item widths are not same. It would be really nice to make every items sizes same as the longest one. For example:
![asd](https://user-images.githubusercontent.com/30001999/56928937-96faa680-6ad8-11e9-8c7b-011620ec927f.png)(item borders are seenable when you `onLongClick`)
As you can see in the picture items widths are not same and users has problem some time about click (because sometimes they click on empty are since view width is smaller than row) . It would be really nice/ergonomic/comfortable if items will take entire row size.

**Comment by PKReejesh** [comment]
You can import the project as a library and then check `QuickAction` class , there will be a line :

` TextView textView = (TextView)inflater.inflate(R.layout.quick_action_item, track, false);`

Set the textview to match parent like this:

```
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:background="?android:attr/selectableItemBackground"
  android:clickable="true"
  android:drawablePadding="4dp"
  android:focusable="true"
  android:gravity="start|center_vertical"
  android:minHeight="48dp"
  android:minWidth="48dp"
  android:orientation="horizontal"
  android:padding="4dp"
  android:textIsSelectable="false"
  />
```
