### ISSUE TITLE
Arrow

### ISSUE THREAD

**Issue by ManoR88** [piruin/quickaction#26]
Hello developer is there a way to hide arrow ... just want to display options only , not pointing arrow

**Comment by piruin** [comment]
There is no way to hide arrow right now. 

But I'm interesting in this one, It may be done on my next free time.
your pull request are also welcome.

**Comment by ManoR88** [comment]
Thank you piruin... hope to see it soon.... 
btw any option like .setCanceledOnTouchOutside() ??  if not plz consider as my request and add this feature dude.

**Comment by piruin** [comment]
https://github.com/piruin/quickaction/issues/32#issuecomment-591216317
