### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by kashban** [piruin/quickaction#3]
Just a big thank you for your efforts to keep this library fresh. I very much appreciate it. 

You'll find it in https://play.google.com/store/apps/details?id=de.kashban.android.picturecalendar [https://play.google.com/store/apps/details?id=de.kashban.android.picturecalendar](Picture Calendar) once I released the next version. 

Cheers!

**Comment by piruin** [comment]
Glad that my work help you, Thank for this issue.
