### ISSUE TITLE
how to change the font size?

### ISSUE THREAD

**Issue by omar201816** [piruin/quickaction#31]

**Comment by piruin** [comment]
It does not support yet. May it be the next release's feature when I have time. A pull request is welcome.

**Comment by piruin** [comment]
Sorry my bad memory. U can change text size by override quick_action_item.xml in your project

**Comment by omar201816** [comment]
Thanks, I could change the style by creating a file with the **".xml"** format called **"quick_action_item.xml"**, in the **layout** folder, with the following design code:

`<?xml version="1.0" encoding="utf-8"?>
<TextView 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:width="60dp"
    android:textAlignment="center"
    android:textSize="10sp" />
`

**Comment by omar201816** [comment]
<?xml version="1.0" encoding="utf-8"?>
<TextView xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_marginLeft="8dp"
    android:layout_marginRight="8dp"
    android:width="60dp"
    android:textAlignment="center"
    android:textSize="10sp" />
