### ISSUE TITLE
Hide Arrow

### ISSUE THREAD

**Issue by saadbzu** [piruin/quickaction#32]
I any update about hide the arrow , show only options?

**Comment by piruin** [comment]
You may try to override resource [`quick_action_horizontal.xml`](https://github.com/piruin/quickaction/blob/master/quickaction/src/main/res/layout/quick_action_horizontal.xml) and/or [`quick_action_vertical`](https://github.com/piruin/quickaction/blob/master/quickaction/src/main/res/layout/quick_action_vertical.xml) on your project, then set visibility of [`arrow_up`](https://github.com/piruin/quickaction/blob/126f9a6fed2becd29424c250ba5e2c55dcbe4091/quickaction/src/main/res/layout/quick_action_vertical.xml#L48) and `arrow_down` as `gone`. I haven't tried yet but it should be work.
