### ISSUE TITLE
quickAction.dismiss() not public

### ISSUE THREAD

**Issue by kashban** [piruin/quickaction#4]
I have a use case where I need to close the popup manually to redraw the icons on the Action Items by reopening it. Unfortunately .dismiss() is no longer available.

Care to change the visibility back to public or does this bear any sideeffects?

**Comment by piruin** [comment]
There is no side effect to be public. Can you create pull request? I will release as 2.1.1

**Comment by piruin** [comment]
@kashban .dismiss() is public now. at version [2.2](https://github.com/piruin/quickaction/releases/tag/2.2) use it with caution!

**Comment by kashban** [comment]
Thank you very much, will test it as soon as I get to work on my app again.
