### ISSUE TITLE
update Title in action

### ISSUE THREAD

**Issue by macdonaldj** [piruin/quickaction#5]
I am able to update the action id, but when i change the title, it doesn't reflect when the popup shows again. or what would be better way to update an existing action? is there a way to remove an action and add a new one?

**Comment by piruin** [comment]
@macdonaldj u can remove then add new one on version [2.2](https://github.com/piruin/quickaction/releases/tag/2.2).

**Comment by macdonaldj** [comment]
great! for now i am just rebuilding the pop up when i need to update it.

**Comment by macdonaldj** [comment]
I'll update and check it out. great library

**Comment by piruin** [comment]
Happy coding
