### ISSUE TITLE
I can't find the latest version code.

### ISSUE THREAD

**Issue by xuhongv** [piruin/quickaction#9]
hellow ! Can you  add the library latest version on the  Redeme.md ?

**Comment by piruin** [comment]
@xuhongv Lastest version is show as download badge on README.md, look like below

[![Download](https://api.bintray.com/packages/blazei/maven/QuickAction/images/download.svg)](https://bintray.com/blazei/maven/QuickAction/_latestVersion)
[![Download](https://jitpack.io/v/piruin/quickaction.svg)](https://jitpack.io/#piruin/quickaction)

currently latest version is 2.3-beta

**Comment by xuhongv** [comment]
oh,but I find the version 2.3 is  sync failed in Android Studio. And the 2.2 is OK.

**Comment by piruin** [comment]
try use `compile 'me.piruin:quickaction:2.3-beta'`
